import { Post, PostService } from "danielbonifacio-sdk";
import Head from "next/head";
import FeaturedPost from "../components/FeaturedPost";

interface HomeProps {
  posts: Post.Paginated;
}

export default function Home(props: HomeProps) {
  const { posts } = props;
  return (
    <div>
      <Head>
        <title>AlgaNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {posts?.content && <FeaturedPost postSummary={posts?.content[0]} />}
    </div>
  );
}

export async function getServerSideProps() {
  const posts = await PostService.getAllPosts({ page: 0 });
  return {
    props: {
      posts,
    },
  };
}
